Multi company refactor
BrunoGodefroy/theodo-form-printer pull request #15
Opened 2017-07-08 12:23 UTC by Samox

2017-07-11 16:24 UTC, BrunoGodefroy requested changes

2017-07-11 16:24 UTC, BrunoGodefroy commented on src/redux/reducer.js
> -      const ids = gapi.selectCompany(action.company)
You need to remove scriptId and clientId from the initial state

2017-07-11 16:24 UTC, BrunoGodefroy commented on src/components/ui/ListForms.jsx
> +    }, 'croute')
I think you can replace that by:

```
const yesOfCourse = this.props.questions.find(question => question.questionSlug === 'recommendation').answers[0]
```

2017-07-11 16:24 UTC, BrunoGodefroy commented on src/components/ui/ListForms.jsx
> +      if (parseInt(form.speed[0]) + parseInt(form.colaboration[0]) >= 8 && form.recommendation === yesOfCourse) {
I think the next step would be to compute that in the backend and add a new field to the form: `successType` that can be either: `wow`, `success` or `red-bucket` 😉

2017-07-11 16:24 UTC, BrunoGodefroy commented on src/components/ui/ProjectForm.jsx
> +                </Segment>)
❤️

2017-07-11 18:39 UTC, Samox commented on src/components/ui/ListForms.jsx
> +      if (parseInt(form.speed[0]) + parseInt(form.colaboration[0]) >= 8 && form.recommendation === yesOfCourse) {
Aight

2017-07-14 09:21 UTC, BrunoGodefroy approved these changes

2017-07-14 09:21 UTC, merged